import { Tray, Menu, nativeImage, app } from 'electron'
import { join } from 'path'
import { revealMainWindow, getMainWindow } from './window'
import enUS from '@shared/i18n/en-US.json'
import zhCN from '@shared/i18n/zh-CN.json'

let tray: Tray | null = null
let trayLocale: 'zh-CN' | 'en-US' = 'zh-CN'

/**
 * A 32×32 sparkle icon for the system tray encoded as base64 PNG.
 * Generated by scripts/generate-icons.py — a 4-point star on an
 * indigo→violet gradient background, readable at tray sizes.
 *
 * This is the fallback when the shipped PNG files can't be loaded.
 */
const TRAY_ICON_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAB9klEQVR4nL2XTU4CMRTH/6/xDngRkZUQ' +
  'ExPYuPZj5cYEBa/AGYYlib+H0JW4VOQcigNk1DxuOwUzQx8DLxkY0M77f/NeO3V68gNoQESUhYCAiJ+U' +
  'M28umKu1cdem/fN4eQsaY4K+KotLUBp8iYAxaUKWCOeD4MK4Y0RAG8J5qzpegC4Br6RRj59Jo5/XVsEM' +
  'UDfNVZ7lEf+4RHjyZlLtXcOEsov6O4S7uH2jQDYcv/Vn133JMAdTsGxtu++CPjdzQ62T7S9CZ714H+8O' +
  'hdsQvt8pEjiPkhBcxDwjDx+VYHoSguC9lkOh8HB/dvyrJTFfBZ3GdDMcToEiuK/VqdzWZ/m0A3TBnOq8' +
  'HbRsuTuaZXhNoAsLoCjmDyuSbh3p1qd8zS2VLpsTXZhwS8qUM34ZdOvj1TH34Jh31kGNJU9D4fMyDOxq' +
  '15zhGbkx2ofBYwiELVXR+nA4c+YhCGyops4z7g+FuzuhlM8XvBAItwqI/0ykyk0C10/VHhqC4T2+Vp0X' +
  'wJmt7JEjGN53AIUwY0xXeX/wJw4+NIlarhD+TcChc8efOxiesJQ9yVuBejuEd2Im3S5gKQ8AhATGdm02' +
  '3t4AEDe21nsWNaEK8KHBuRdbDp29ao4X9BzC5yLAfxIP7S/sAAAAAElFTkSuQmCC',
  'base64'
)

/**
 * Build the tray image.
 * On macOS we resize to 16×16 and set as template so it adapts to light/dark.
 * On Windows / Linux we prefer loading from a shipped PNG file, which Electron
 * converts to .ico internally; falling back to the hardcoded base64.
 */
function createTrayImage(): Electron.NativeImage {
  // 1. Try the shipped tray icon files (works in dev and packaged asar)
  const candidates = [
    join(__dirname, '../../build/icon-tray-32.png'),
    join(__dirname, '../build/icon-tray-32.png'),
    join(process.resourcesPath || '', 'build/icon-tray-32.png'),
    join(process.resourcesPath || '', 'icon-tray-32.png'),
  ]
  for (const p of candidates) {
    try {
      const img = nativeImage.createFromPath(p)
      if (!img.isEmpty()) {
        if (process.platform === 'darwin') {
          img.resize({ width: 16, height: 16 })
          img.setTemplateImage(true)
        }
        return img
      }
    } catch { /* skip */ }
  }

  // 2. Fallback: hardcoded base64 PNG
  const bufImg = nativeImage.createFromBuffer(TRAY_ICON_PNG)
  if (!bufImg.isEmpty()) {
    if (process.platform === 'darwin') {
      bufImg.resize({ width: 16, height: 16 })
      bufImg.setTemplateImage(true)
    }
    return bufImg
  }

  // 3. Last resort: empty image (tray will have a blank placeholder,
  //    which is still better than crashing during startup).
  console.error('[EasyPrompt] Failed to create tray image — all sources exhausted.')
  return nativeImage.createEmpty()
}

/** Get a translated label for the current app language. */
function t(key: string): string {
  const locale = trayLocale === 'zh-CN' ? zhCN : enUS
  const keys = key.split('.')
  let val: unknown = locale
  for (const k of keys) {
    if (typeof val === 'object' && val !== null) {
      val = (val as Record<string, unknown>)[k]
    }
  }
  return typeof val === 'string' ? val : key
}

/** Create the system tray icon. Call after config is loaded. */
export function createTray(language: 'zh-CN' | 'en-US' = 'zh-CN'): Tray {
  trayLocale = language

  const image = createTrayImage()

  tray = new Tray(image)
  tray.setToolTip('EasyPrompt')

  tray.setContextMenu(buildTrayMenu())

  // Click the icon to toggle window visibility (show/hide).
  tray.on('click', () => {
    const win = getMainWindow()
    if (!win) return
    // Toggle: hide if currently visible & focused, otherwise reveal.
    if (win.isVisible() && win.isFocused()) {
      win.hide()
    } else {
      if (win.isMinimized()) win.restore()
      if (!win.isVisible()) win.show()
      win.focus()
    }
  })

  return tray
}

/** Rebuild and reassign the tray context menu (e.g. after language change). */
export function rebuildTrayMenu(language?: 'zh-CN' | 'en-US'): void {
  if (language) trayLocale = language
  if (!tray || tray.isDestroyed()) return
  tray.setContextMenu(buildTrayMenu())
}

function buildTrayMenu(): Electron.Menu {
  return Menu.buildFromTemplate([
    {
      label: t('tray.show'),
      click: () => revealMainWindow()
    },
    { type: 'separator' },
    {
      label: t('tray.newPrompt'),
      click: () => {
        revealMainWindow()
        const win = getMainWindow()
        win?.webContents.send('tray:new-prompt')
      }
    },
    {
      label: t('tray.settings'),
      click: () => {
        revealMainWindow()
        const win = getMainWindow()
        win?.webContents.send('tray:open-settings')
      }
    },
    { type: 'separator' },
    {
      label: t('tray.quit'),
      click: () => {
        // Bypass the hide-to-tray close handler.
        app.quit()
      }
    }
  ])
}

export function destroyTray(): void {
  tray?.destroy()
  tray = null
}
